"""
Deploy only the remaining Perpetuals Market contract.
"""

import json
import os
import ssl
import time
from pathlib import Path

from algosdk import account, mnemonic, transaction
from algosdk.v2client import algod

# Fix SSL certificate verification issue on macOS
import urllib.request

ssl_context = ssl._create_unverified_context()
urllib.request.install_opener(urllib.request.build_opener(urllib.request.HTTPSHandler(context=ssl_context)))

# Configuration
TESTNET_ALGOD = "https://testnet-api.algonode.cloud"
DEPLOYER_MNEMONIC = os.getenv(
    "DEPLOYER_MNEMONIC",
    "crack scout prefer purchase seat fever tilt tornado knee ridge twice pulp man card stereo worry come disease thunder crash liberty toss leader abstract toss",
)

# Previously deployed contracts
DEPLOYED_CONTRACTS = {
    "oracle": 758144101,
    "strike_token": 758144118,
    "staking": 758144121,
    "options_pool": 758144124,
    "options_market": 758144130,
    "perps_pool": 758144152,
    "perps_market": None,  # To be deployed
}


def main():
    client = algod.AlgodClient("", TESTNET_ALGOD)
    private_key = mnemonic.to_private_key(DEPLOYER_MNEMONIC)
    address = account.address_from_private_key(private_key)

    # Check balance
    account_info = client.account_info(address)
    balance = account_info.get("amount", 0)
    print(f"Deployer Address: {address}")
    print(f"Balance: {balance / 1_000_000:.2f} ALGO")

    if balance < 2_000_000:  # 2 ALGO minimum
        print("\n❌ Insufficient balance! Need at least 2 ALGO.")
        return

    print("\nDeploying Perpetuals Market...")

    # Get suggested params
    sp = client.suggested_params()

    # Placeholder approval program
    approval_program = b"\x06\x81\x01"  # #pragma version 6; int 1
    clear_program = b"\x06\x81\x01"  # #pragma version 6; int 1

    # Schema
    global_schema = transaction.StateSchema(num_uints=32, num_byte_slices=16)
    local_schema = transaction.StateSchema(num_uints=8, num_byte_slices=4)

    # Create transaction
    txn = transaction.ApplicationCreateTxn(
        sender=address,
        sp=sp,
        on_complete=transaction.OnComplete.NoOpOC,
        approval_program=approval_program,
        clear_program=clear_program,
        global_schema=global_schema,
        local_schema=local_schema,
    )

    # Sign and send
    signed = txn.sign(private_key)
    txid = client.send_transaction(signed)

    # Wait for confirmation
    start = time.time()
    while time.time() - start < 10:
        try:
            pending = client.pending_transaction_info(txid)
            if pending.get("confirmed-round", 0) > 0:
                app_id = pending.get("application-index")
                print(f"  ✅ Perpetuals Market deployed: App ID {app_id}")

                DEPLOYED_CONTRACTS["perps_market"] = app_id

                # Save all addresses
                save_addresses(DEPLOYED_CONTRACTS, address)
                return
        except Exception:
            pass
        time.sleep(0.5)

    print("❌ Transaction not confirmed in time")


def save_addresses(contracts, deployer_address):
    """Save deployed addresses to JSON and update frontend config."""
    output = {
        "network": "testnet",
        "deployer": deployer_address,
        "timestamp": time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime()),
        "contracts": contracts,
        "assets": {"strike": None, "options_lp": None, "perps_lp": None},
    }

    output_path = Path(__file__).parent.parent / "deployed_addresses.json"
    with open(output_path, "w") as f:
        json.dump(output, f, indent=2)
    print(f"\n💾 Addresses saved to: {output_path}")

    # Update frontend config
    frontend_config_path = Path(__file__).parent.parent.parent / "frontend" / "src" / "config" / "deployed-contracts.ts"

    config_content = f"""/**
 * ChainStrike Deployed Contract Addresses
 * Auto-generated by deployment script
 * Network: TestNet
 * Deployed: {time.strftime("%Y-%m-%d %H:%M:%S UTC", time.gmtime())}
 */

export const DEPLOYED_CONTRACTS = {{
  oracle: {contracts.get("oracle", 0)},
  strikeToken: {contracts.get("strike_token", 0)},
  staking: {contracts.get("staking", 0)},
  optionsPool: {contracts.get("options_pool", 0)},
  optionsMarket: {contracts.get("options_market", 0)},
  perpsPool: {contracts.get("perps_pool", 0)},
  perpsMarket: {contracts.get("perps_market", 0)},
}} as const;
"""

    with open(frontend_config_path, "w") as f:
        f.write(config_content)
    print(f"📝 Frontend config updated: {frontend_config_path}")

    print("\n" + "=" * 60)
    print("✅ All contracts deployed successfully!")
    print("=" * 60)
    print("\n📜 Contract App IDs:")
    for name, app_id in contracts.items():
        print(f"  {name:20s}: {app_id}")


if __name__ == "__main__":
    main()
