/**
 * ChainStrike Deployed Contract Addresses
 * Auto-generated by deployment script
 * Network: TestNet
 * Last Updated: 2026-04-04 (1-minute options support)
 * 
 * Updated Features:
 * - Options Market: 1-minute to 30-day expiry, time-based IV scaling
 * - Options Pool: Cross-contract calls for premium/settlement accounting
 */

export const DEPLOYED_CONTRACTS = {
  oracle: 758189767,
  strikeToken: 758189778,
  staking: 758189780,
  optionsPool: 758222938,
  optionsMarket: 758254794,  // Updated: 1-minute options support
  perpsPool: 758190050,
  perpsMarket: 758190064,
} as const;

export type ContractName = keyof typeof DEPLOYED_CONTRACTS;
